import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Crypto Data App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <header className="p-6">
          <nav className="flex justify-around text-lg">
            <Link href="/">Home</Link>
            <Link href="/crypto">Crypto Categories</Link>
            <Link href="/about">About</Link>
          </nav>
        </header>

        <h1 className="text-center mt-3 mb-5">
          Top 20 Cryptocurrencies By Market Cap
        </h1>

        <div className="flex flex-wrap justify-center m-5 gap-5">
          {data.map((coin) => {
            const dateUpdated = new Date(coin.last_updated).toLocaleString();
            const coinPrice = new Intl.NumberFormat("en-US", {
              style: "currency",
              currency: "USD",
              minimumFractionDigits: 2,
              maximumFractionDigits: 20,
            }).format(coin.current_price);

            const coinPriceChange = new Intl.NumberFormat("en-US", {
              style: "percent",
              minimumFractionDigits: 2,
              maximumFractionDigits: 2,
            }).format(coin.price_change_percentage_24h / 100);

            return (
              <div
                key={coin.id}
                className="p-3 w-1/4 border-2 rounded-md shadow-sm hover:shadow-lg"
              >
                <Link href={`/${coin.id}`} className="flex flex-col">
                  <Image
                    className="self-center"
                    src={coin.image}
                    alt={coin.name}
                    width="100"
                    height="100"
                  />
                  <h2 className="self-center">{coin.name}</h2>
                  <p>Symbol: {coin.symbol}</p>
                  <p>Price: {coinPrice}</p>
                  <p>24hr: {coinPriceChange}</p>
                  <p>Updated: {dateUpdated}</p>
                </Link>
              </div>
            );
          })}
        </div>
      </main>
      <footer className="m-3 text-center">Burak Aydemir Development</footer>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch(
    "https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=20&page=1&sparkline=false"
  );
  const data = await res.json();

  if (!data) {
    return {
      notFound: true,
    };
  }

  return {
    props: {
      data,
    },
  };
}
